apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronologicalearth-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronologicalearth-crawler
  template:
    metadata:
      labels:
        app: chronologicalearth-crawler
    spec:
      containers:
      - image: chronologicalearth/chronologicalearth-crawler
        name: chronologicalearth-crawler

---

apiVersion: v1
kind: Service
metadata:
  name: chronologicalearth-crawler
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "chronologicalearth-crawler"
    port: 8086
  selector:
    app: chronologicalearth-crawler
